from reportlab.lib.pagesizes import A5
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.platypus.flowables import HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
import io
import logging
from datetime import datetime
from models import ExtractionResult

logger = logging.getLogger(__name__)


def generate_prescription_pdf(result: ExtractionResult) -> bytes:
    """
    Generate a clean, printable PDF of the structured prescription.
    
    Layout:
    - Header: "PrescriptionReader" logo text + "Digital Prescription Record" subtitle
    - Patient info box: name, date, doctor
    - Medicines table: columns = Medicine | Dosage | Frequency | Duration | Instructions
      Color-code rows: green bg for fda_verified, yellow for india_db only, white for unverified
      Show confidence as a small percentage in the medicine name cell
    - General instructions section (if present)
    - Follow-up date callout box (if present)
    - Footer: "Generated by PrescriptionReader · This is a digital copy, not a prescription"
              + confidence disclaimer
    - Page size: A5 (148mm x 210mm) — fits on mobile screens and pharmacy printers
    
    Returns: bytes (PDF content)
    """
    
    try:
        # Create PDF buffer
        buffer = io.BytesIO()
        
        # Create document with A5 page size
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A5,
            rightMargin=15*mm,
            leftMargin=15*mm,
            topMargin=15*mm,
            bottomMargin=15*mm
        )
        
        # Get styles
        styles = getSampleStyleSheet()
        
        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=18,
            spaceAfter=6,
            alignment=TA_CENTER,
            textColor=colors.HexColor('#2563eb')
        )
        
        subtitle_style = ParagraphStyle(
            'CustomSubtitle',
            parent=styles['Normal'],
            fontSize=10,
            spaceAfter=12,
            alignment=TA_CENTER,
            textColor=colors.grey
        )
        
        section_style = ParagraphStyle(
            'SectionHeader',
            parent=styles['Heading2'],
            fontSize=12,
            spaceAfter=6,
            spaceBefore=12,
            textColor=colors.HexColor('#1f2937')
        )
        
        normal_style = ParagraphStyle(
            'CustomNormal',
            parent=styles['Normal'],
            fontSize=9,
            spaceAfter=3
        )
        
        # Build document content
        story = []
        
        # Header
        story.append(Paragraph("PrescriptionReader", title_style))
        story.append(Paragraph("Digital Prescription Record", subtitle_style))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey))
        story.append(Spacer(1, 8))
        
        # Patient Information Box
        patient_data = [
            ['Patient Name:', result.patient_name or '—'],
            ['Date:', result.date or '—'],
            ['Doctor:', result.doctor_name or '—'],
            ['Registration No:', result.doctor_reg_no or '—']
        ]
        
        patient_table = Table(patient_data, colWidths=[35*mm, 65*mm])
        patient_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f8fafc')),
            ('BORDER', (0, 0), (-1, -1), 1, colors.lightgrey),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 9),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('LEFTPADDING', (0, 0), (-1, -1), 6),
            ('RIGHTPADDING', (0, 0), (-1, -1), 6),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ]))
        
        story.append(patient_table)
        story.append(Spacer(1, 12))
        
        # Medicines Section
        if result.medicines:
            story.append(Paragraph("Prescribed Medicines", section_style))
            
            # Prepare medicine table data
            medicine_headers = ['Medicine', 'Dosage', 'Frequency', 'Duration', 'Instructions']
            medicine_data = [medicine_headers]
            
            for med in result.medicines:
                # Format medicine name with confidence
                med_name = med.name
                if med.confidence < 1.0:
                    med_name += f" ({int(med.confidence * 100)}%)"
                
                row = [
                    med_name,
                    med.dosage or '—',
                    med.frequency or '—',
                    med.duration or '—',
                    med.instructions or '—'
                ]
                medicine_data.append(row)
            
            # Create medicine table
            medicine_table = Table(medicine_data, colWidths=[30*mm, 20*mm, 20*mm, 20*mm, 30*mm])
            
            # Base table style
            table_style = [
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e5e7eb')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
                ('TOPPADDING', (0, 1), (-1, -1), 4),
                ('BOTTOMPADDING', (0, 1), (-1, -1), 4),
                ('LEFTPADDING', (0, 0), (-1, -1), 4),
                ('RIGHTPADDING', (0, 0), (-1, -1), 4),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ]
            
            # Add color coding for verification status
            for i, med in enumerate(result.medicines, 1):
                if med.fda_verified:
                    # Green background for FDA verified
                    table_style.append(('BACKGROUND', (0, i), (-1, i), colors.HexColor('#dcfce7')))
                elif med.india_db_verified:
                    # Yellow background for India DB verified
                    table_style.append(('BACKGROUND', (0, i), (-1, i), colors.HexColor('#fef3c7')))
                elif med.confidence < 0.4:
                    # Light red background for low confidence
                    table_style.append(('BACKGROUND', (0, i), (-1, i), colors.HexColor('#fee2e2')))
            
            medicine_table.setStyle(TableStyle(table_style))
            story.append(medicine_table)
            
            # Medicine verification legend
            legend_data = [
                ['Legend:', ''],
                ['Green = FDA Verified', 'Yellow = India DB Verified'],
                ['White = Unverified', 'Red = Low Confidence (<40%)']
            ]
            
            legend_table = Table(legend_data, colWidths=[50*mm, 50*mm])
            legend_table.setStyle(TableStyle([
                ('FONTNAME', (0, 0), (0, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 7),
                ('TEXTCOLOR', (0, 0), (-1, -1), colors.grey),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ]))
            
            story.append(Spacer(1, 6))
            story.append(legend_table)
        
        # General Instructions
        if result.general_instructions:
            story.append(Spacer(1, 12))
            story.append(Paragraph("General Instructions", section_style))
            
            instructions_style = ParagraphStyle(
                'Instructions',
                parent=normal_style,
                leftIndent=10,
                rightIndent=10,
                spaceAfter=6,
                borderWidth=1,
                borderColor=colors.lightgrey,
                borderPadding=8,
                backColor=colors.HexColor('#f8fafc')
            )
            
            story.append(Paragraph(result.general_instructions, instructions_style))
        
        # Follow-up Date
        if result.followup_date:
            story.append(Spacer(1, 12))
            
            followup_style = ParagraphStyle(
                'Followup',
                parent=normal_style,
                alignment=TA_CENTER,
                fontSize=10,
                textColor=colors.HexColor('#059669'),
                borderWidth=1,
                borderColor=colors.HexColor('#10b981'),
                borderPadding=8,
                backColor=colors.HexColor('#ecfdf5')
            )
            
            story.append(Paragraph(f"<b>Follow-up Date: {result.followup_date}</b>", followup_style))
        
        # Confidence Summary
        story.append(Spacer(1, 12))
        
        high_confidence_count = sum(1 for med in result.medicines if med.confidence >= 0.8)
        total_medicines = len(result.medicines)
        
        confidence_text = f"Extraction Summary: {high_confidence_count} of {total_medicines} medicines extracted with high confidence (≥80%)"
        ocr_confidence_text = f"OCR Quality: {int(result.ocr_confidence * 100)}%"
        
        story.append(Paragraph(confidence_text, normal_style))
        story.append(Paragraph(ocr_confidence_text, normal_style))
        
        # Processing info
        processing_text = f"Processing Time: {result.processing_time_ms}ms | Model: {result.model_used}"
        story.append(Paragraph(processing_text, normal_style))
        
        # Extraction failures (if any)
        if result.extraction_failures:
            story.append(Spacer(1, 6))
            failures_text = "Note: Some fields could not be extracted clearly: " + ", ".join(result.extraction_failures)
            
            failure_style = ParagraphStyle(
                'Failures',
                parent=normal_style,
                textColor=colors.HexColor('#dc2626'),
                fontSize=8
            )
            
            story.append(Paragraph(failures_text, failure_style))
        
        # Footer
        story.append(Spacer(1, 20))
        
        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=7,
            alignment=TA_CENTER,
            textColor=colors.grey,
            borderWidth=1,
            borderColor=colors.lightgrey,
            borderPadding=6,
            backColor=colors.HexColor('#fafafa')
        )
        
        footer_text = f"""Generated by PrescriptionReader on {datetime.now().strftime('%Y-%m-%d %H:%M')}
        <br/>
        <b>This is a digital copy for reference only, not a prescription for dispensing medicines.</b>
        <br/>
        Confidence scores indicate AI model certainty. Please verify with original prescription."""
        
        story.append(Paragraph(footer_text, footer_style))
        
        # Build PDF
        doc.build(story)
        
        # Get PDF bytes
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        logger.info(f"Generated PDF for prescription {result.id}, size: {len(pdf_bytes)} bytes")
        
        return pdf_bytes
        
    except Exception as e:
        logger.error(f"PDF generation failed: {e}")
        # Return a minimal error PDF
        return _generate_error_pdf(str(e))


def _generate_error_pdf(error_message: str) -> bytes:
    """Generate a simple error PDF when main generation fails"""
    try:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A5)
        
        styles = getSampleStyleSheet()
        story = [
            Paragraph("PrescriptionReader", styles['Title']),
            Spacer(1, 20),
            Paragraph("PDF Generation Error", styles['Heading2']),
            Spacer(1, 12),
            Paragraph(f"An error occurred while generating the PDF: {error_message}", styles['Normal']),
            Spacer(1, 12),
            Paragraph("Please try again or contact support.", styles['Normal'])
        ]
        
        doc.build(story)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        return pdf_bytes
        
    except Exception as e:
        logger.error(f"Error PDF generation also failed: {e}")
        # Return empty bytes as last resort
        return b""